### ISSUE TITLE
Adicionar indicador de muitos caracteres no comentário e permitir tamanho negativo no front

### ISSUE THREAD

**Issue by tprei** [Projeto-USPY/uspy-features#19]
![image](https://user-images.githubusercontent.com/37089330/149232645-f59fcfdf-e972-4ade-8940-c1ab767b7d93.png)

**Comment by lucasturci** [comment]
Esse é o tipo de task que vc coloca 2 de dificuldade na planning mas vira 15

Mas ta ai:
![image](https://user-images.githubusercontent.com/17186683/152665648-ab40fb9b-6002-4e3b-b7ae-fad2352c0c58.png)
