### ISSUE TITLE
Adicionar botões de like e dislike de disciplina no histórico interativo

### ISSUE THREAD

**Issue by tprei** [Projeto-USPY/uspy-features#20]

**Comment by lucasturci** [comment]
**Mobile**

![image](https://user-images.githubusercontent.com/17186683/152036562-60885f32-2b21-410c-8540-b9c4770301a9.png)

**Desktop**

![image](https://user-images.githubusercontent.com/17186683/152036709-21e203a6-1d2a-4328-9088-ad0bd15bf7cb.png)
